pipeline {
    agent any

    environment {
        NODEJS_HOME: "/home/ilia/.nvm/versions/node/v20.11.1/bin/node"
        PATH = "$NODEJS_HOME/bin:$PATH"
    }

    stages {
        stage("Checkout") {
            steps {
                git branch: "master",
                url: "https://github.com/Fugazzii/fugazzi-blog"
            }
        }

        stage("Install") {
            steps {
                sh "npm install"
            }
        }

        stage("Deploy") {
            steps {
                sh "npx sls deploy"
            }
        }
    }

    post {
        success {
            echo "Deployment successful!"
        }
        failure {
            echo "Deployment failed!"
        }
    }
}