pipeline {
    agent any

    stages {
        stage("Checkout") {
            steps {
                git branch: "master",
                url: "https://github.com/Fugazzii/fugazzi-blog"
            }
        }

        stage("Install") {
            steps {
                sh "npm install"
            }
        }

        stage("Deploy") {
            steps {
                sh "npx sls deploy"
            }
        }

    }
}